a<-read.table("household_power_consumption.txt",sep =";",header = TRUE,na.strings = "?")
b<-as.Date(a$Date,format = "%d/%m/%Y")
x<-as.Date("2007-02-01")
y<-as.Date("2007-02-02")
c<-b == x| b == y
a<-a[c,]
par(mfrow=c(2,2))
plot(a$Global_active_power,xlab = " ", ylab = "Global Active Power(kilowatts)",type = "n" )
lines(a$Global_active_power)
plot(a$Voltage,xlab = "Datetime",ylab = "Voltage",type = "n")
lines(a$Voltage)
plot(a$Sub_metering_1,xlab = " ",ylab = "Energy sub metering",type = "n")
lines(a$Sub_metering_1,col ="black")
lines(a$Sub_metering_2,col ="red")
lines(a$Sub_metering_3,col ="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = 1,col = c("black","red","blue"))
plot(a$Global_reactive_power ,xlab = "Datetime",ylab = "Global_reactive_power",type = "n")
lines(a$Global_reactive_power)
dev.copy(png,"plot4.png")